---
sign_in: تسجيل الدخول
sign_up: اشترك
agent_panel: لوحة الوكيل
admin_panel: لوحة الادارة
country: البلد
city:
register: سجل
details: تفاصيل
view_all: عرض جميع
order_by: الترتيب حسب
none: لا أحد
terms_and_conditions: شروط والحالة
reg_success_message: تسجيل حسابك ناجحا. تم إرسال رسالة إلكترونية إلى البريد الإلكتروني الخاص بك. يرجى اتباع هذا البريد الالكتروني لتفعيل account.Thanks بك
recover: استرداد
oops: عفوا، لم يتم العثور على الصفحة
address: عنوان
all: جميع
contact_us: اتصل بنا
confirmation: تأكيد
tags: العلامات
login: دخول
post_not_found: آخر لم يتم العثور على
view_more: عرض المزيد
image: صورة
create: إنشاء
send: إرسال
contact_subject: البريد الالكتروني للاتصال
password: كلمة المرور
confirm_password: تأكيد كلمة المرور
all_posts: جميع المشاركات
no_posts: لا يوجد ردود
title: العنوان
description:
status: الحالة
actions: تطبيقات
type: نوع
type_something: اكتب شيئا
content: المحتوى
category: الفئة
all_categories: كل الفئات
edit_category: تحرير الفئة
new_category: فئة جديدة
edit: تحرير
delete: حذف
name: اسم
save: حفظ
no_parent: لا الأم
add_another: إضافة أخرى
export_to_file: تصدير إلى ملف
options: الخيارات
all_pages: جميع الصفحات
no_pages: لا توجد صفحات
manage_menu: القائمة إدارة
menu_title: العنوان القائمة
menu_alias: الاسم المستعار القائمة
show_in_menu: عرض في القائمة
page_layout: تخطيط الصفحة
content_from: المحتوى من
url: رابط
seo_options: خيارات SEO
meta_description: وصف ميتا
key_words: الكلمات الدالة
crawl_after: الزحف بعد (أيام)
all_plugins: جميع الإضافات
no_plugins: لا الإضافات
name_and_version: اسم وإصدار
change_password: تغيير كلمة المرور
current_password: كلمة المرور الحالية
new_password: كلمة المرور الجديدة
retype_password: إعادة كتابة كلمة المرور
password_reset_info_msg: يرجى أولا تعيين الخاص بك كلمة السر الجديدة
edit_profile: تعديل الملف الشخصي
profile_picture: صورة الملف الشخصي
username: كلمة
email: البريد الإلكتروني
first_name: الاسم الأول
last_name: اسم العائلة
gender: الجنس
phone: الهاتف
company_name: اسم الشركة
about_me: معلومات عني
facebook_account: حساب الفيسبوك
twitter_account: حساب التغريد
linkedin_account: حساب ينكدين
gp_account: حسابك في + Google
account_msg: Please enter the link, without http: //
contact_email: البريد الالكتروني للاتصال
webadmin_name: Webadmin اسم
webadmin_email: Webadmin البريد الإلكتروني
update: تحديث
upload: تحميل
site_settings: إعدادات الموقع
site_title: عنوان الموقع
footer_text: تذييل النص
site_logo: شعار الموقع
site_language: اختر لغة الموقع
site_text_direction: الموقع اتجاه النص
per_page: ترقيم الصفحات لكل صفحة
default_page_layout: تخطيط الصفحة الافتراضية
smtp_email_settings: إعدادات SMTP البريد الإلكتروني
smtp_email: SMTP البريد الإلكتروني
smtp_host: SMTP المضيف
smtp_port: ميناء SMTP
smtp_timeout: مهلة SMTP
smtp_user: SMTP العضو
smtp_password: SMTP كلمة المرور
generate_site_map: إنشاء خريطة الموقع
sitemap_info_msg: NB: الرجاء تحديد التي تريد إدراجها على خريطة الموقع XML. يتم حفظ بعد نجاح الجيل sitemap.xml تحت الدليل الجذر. يمكنك أيضا تحرير هذا الملف لإدراج عناوين المواقع الخاصة بك.
pages: الصفحات
view_xml: عرض XML
create_xml: إنشاء XML
manage_backups: إدارة النسخ الاحتياطية
create_sql_backup: إنشاء SQL النسخ الاحتياطي
create_image_backup: إنشاء صورة النسخ الاحتياطي
restore: استعادة
download: تحميل
dashboard: لوحة القيادة
overview_stats_more: نظرة عامة، الإحصائيات وأكثر
visit_site: زيارة الموقع
logout: خروج
themes: ثيمات
locations: المواقع
profile:
agents: وكلاء
widgets: الحاجيات
all_widgets: جميع الحاجيات
widget_positions: مواقف القطعة
new_post: وظيفة جديدة
pages_and_menu: الصفحات والقائمة
new_page: صفحة جديدة
menu: القائمة
system: نظام
edit_email_text: تحرير نص البريد الإلكتروني
admin_settings: إعدادات المشرف على شبكة الإنترنت
sitemap: خريطة الموقع
activate: تنشيط
active_theme: الموضوع النشط
available_themes: ثيمات المتوفرة
all_users: جميع المستخدمين
create_user: إنشاء العضو
export_user_email: رسائل البريد الإلكتروني تصدير العضو (CSV.)
profile_info: معلومات الملف الشخصي
manage_menu: إدارة القائمة
edit_page: تحرير صفحة
create_widget: إنشاء القطعة
widget_name: اسم القطعة
activate_deactivate: تنشيط / دي تنشيط
show: عرض
available_widgets: متوفر الحاجيات
active_widgets: الحاجيات النشطة
delete_warning: هل تريد بالتأكيد حذف لا.
yes:' أجل'
no: لا'
fa_icon: FA الدرجة أيقونة
post_ad: آخر الإعلانات
post_ad_subtitle: وضع التفاصيل إعلانك
signin: تسجيل الدخول من
signup: الاشتراك
signup_title: إنشاء حسابك
not_found: لم يتم العثور على
purpose: الغرض
select_category: اختر الفئة
address: عنوان
upload_later_msg: عليك أن تكون قادرا على تحميل الصور معرض ورابط الفيديو بعد إنشاء آخر
user_panel: لوحة العضو
logout: خروج
all_posts: جميع المشاركات
put_as_comma_seperated: كما وضع (،) فاصلة sperated
added: أضيفت
location: الموقع
views: المشاهدات
add_new: إضافة جديد
search: بحث
contact_mode: الاتصال الوضع
reset: إعادة تعيين
contact: الاتصال
type_your_message: اكتب رسالتك هنا ..
mail_sent: البريد المرسل
home: الصفحة الرئيسية
list_your_ad: إدراج إعلانك
print: طباعة
remember_me: حفظ البيانات
forgot_password: نسيت كلمة السر
login_to_your_account: تسجيل الدخول إلى حسابك
register_your_account: سجل حسابك
male: ذكر
female: أنثى
state: الدولة
users: المستخدمين
ads: إعلانات
categories: الفئات
top_posts: أعلى معدل المشاركات
default_site_settings: افتراضي إعدادات الموقع
webadmin_settings: إعدادات Webadmin
banner_settings: إعدادات راية
logged_in_as: تم تسجيل الدخول باسم
password_change_success: password_change_success
email_sent_inbox: A البريد الإلكتروني هو نرسل للكم inbox.Check أن البريد الإلكتروني.
password_recovery_link_invalid: استعادة كلمة السر لينك غير صالح
user_updated: العضو التحديث
user_deleted: العضو محذوفة
data_inserted: بيانات إدراج
data_updated: بيانات محدثة
settings_updated: الإعدادات المحدثة
page_updated: صفحة محدثة
page_created: تم إنشاء الصفحة
page_deleted: صفحة محذوفة
menu_updated: القائمة حدثت في
site_map_generation_success: خريطة الموقع ولدت بنجاح.
select_option: الرجاء تحديد أو خيارات أكثر مختارة.
image_backup_created: صورة النسخ الاحتياطي مكون
language_translated: ترجمت اللغة
backup_deleted: النسخ الاحتياطي محذوفة
database_restored: قاعدة البيانات المستعادة
theme_activated: موضوع نشط
user_created: العضو مكون
widget_position_updated: القطعة المركز تحديث
widget_created: القطعة مكون
settings_updated: الإعدادات المحدثة
widget_data_updated: القطعة البيانات المحدثة
unable_to_write_widget: غير قادر على كتابة القطعة
admin_change_pass_help: اترك فارغة إذا لم تغير حاجة
login_with_google: تسجيل الدخول مع جوجل
login_with_facebook: تسجيل الدخول مع الفيسبوك
register_for_new_account : سجل للحصول على حساب جديد
site_map : خريطة الموقع
show_site_map : عرض خريطة الموقع
about : حول
see_full_documentation: راجع وثائق كاملة
edit_profile: تعديل الملف الشخصي
admin: المشرف
re_password: إعادة كتابة كلمة المرور
explain_widget_position: شرح المواقف القطعة
new_ad: إعلان جديد
select_one: اختر واحدة
username_or_email: اسم المستخدم أو البريد الالكتروني
post_detail: آخر التفاصيل
edit_user: تحرير المستخدم
the_field_is_required: مطلوب الحقل ق٪.
valid_email: حقل ق٪ يجب أن يحتوي على عنوان بريد إلكتروني صالح.
min_length: حقل ق٪ يجب أن يكون أحرف على الأقل٪ الصورة في الطول.
numeric: يجب أن يحتوي الحقل على الصورة٪ أرقام فقط.
matches: لا مجال ليالي٪ لا تتطابق حقل٪ الصورة.
greater_than: يجب أن يحتوي الحقل على الصورة٪ عدد أكبر من٪ الصورة.
must_accept_terms: يجب قبول الشروط والأحكام
dont_have_permission: ليس لديك صلاحية لدخول لهذه الصفحة
email_allready_in_use: البريد الإلكتروني قيد الاستخدام
username_allready_in_use: اسم المستخدم allready قد تكون قيد الاستعمال
current_password_not_matched: كلمة المرور الحالية ديدن \ 'ر المباراة
email_not_matched: البريد الإلكتروني غير متطابق
account_not_confirmed: الحساب غير مؤكدة
unique_alias: حقل ق٪ يحتاج لتكون فريدة من نوعها
smtp_email_settings: إعدادات SMTP البريد الإلكتروني
error_occured: حدث خطأ. يرجى التحقق من الحقول أدناه
user_profile: نبذة عن المستخدم '
user_email: البريد الإلكتروني للمستخدم
target_lang_name: لغة الهدف
enable_signup: تمكين الاشتراك
facebook_app_settings: الفيسبوك إعدادات التطبيق
enable_facebook_login: تمكين الفيسبوك تسجيل الدخول
fb_app_id: الفيسبوك التطبيق معرف
fb_secret_key: الفيسبوك المفتاح السري
comment_settings: ضبط تعليق
enable_comment: تمكين تعليق
disqus_shortname: هارد Shortname
active_widget_position: موقف القطعة نشط
upload_and_install: تحميل وتثبيت
install_updates: تثبيت التحديثات / ثيمات / الإضافات / الحاجيات
click_and_edit: حدد ملف القالب ثم انقر فوق تحرير
google_analytics_settings: AnalyticsSettings جوجل
default_seo_settings: إعدادات SEO افتراضي
find_us_on_facebook: تابعنا في الفيسبوك
type_anything: اكتب أي شيء
login_failed : فشل تسجيل الدخول
debug_email : التصحيح البريد الإلكتروني
email_to : لالبريد الإلكتروني
ive_read_the: لقد قرأت
title_city_category: العنوان، المدينة أو الفئة
css_compression: دمج جميع الملفات المغلق
all_sub_categories : جميع التصنيفات الفرعية
no_sub_categories : لا التصنيفات الفرعية
email_cleared: البريد الإلكتروني مسح
hide_users_profile_phone: إخفاء الهاتف للمستخدمين الشخصي
features: الميزات
content: المحتوى
news_urls: مصدر جديد
all_sources: جميع المصادر
addsource: إضافة المصدر
new_source: مصدر جديد
seo_keywords : سيو كلمات
seo_description : سيو الوصف
all_news : جميع الأخبار
new_news : أخبار جديدة
create_news : إنشاء الأخبار
edit_news : تحرير أخبار
no_source : لا المصدر
no_category : لا الفئة
sub_category : التصنيف الفرعي
category_2: S.Category
news_updated: الأخبار المحدثة
news_added: الأخبار التي تم إنشاؤها
source: المصدر
link: رابط
media: وسائل الإعلام
put_as_comma_separated: ضع كما فاصلة (،) فصل الشكل
site_settings: إعدادات الموقع
clear_old_news: أخبار قديمة واضح
news_before: أخبار قبل
leave_empty_if_doesnot_matter: اترك فارغا إذا لا يهم
view_less_than: عرض أقل من
without_image: بدون صورة
you_cant_undo_this_action: لا يمكن التراجع عن هذا الإجراء
news_deleted: أخبار تطهيرها
general: عام
moderator: مشرف
genaral_user_can_create_post: يمكن للمستخدم إنشاء الأخبار
moderator_can_create_post: مشرف يمكن أن تخلق الأخبار
auto_crawl: السيارات الزحف
lazy_load_images: تحميل الصور كسول
generate_widgets: توليد الحاجيات
sidebar: الشريط الجانبي
pagebody: Pagebody
widget_generated: القطعة المتولدة
widget_generation_failed: جيل القطعة فشل
latest_news: آخر الأخبار
news_by: عن طريق
top_news: توب نيوز
source_added: واضاف المصدر
no_news_found: لا أنباء
clear: واضح
view_news_in: مشاهدة الأخبار في
seen_by: مشاهدة
read_this_on: اقرأ هذا على
news_source: أخبار من مصدر
news_category: أخبار من فئة
source_name: اسم
parent_category: المنتدى الرئيسي
news_grabbed: أخبار أمسك بنجاح
rss_url: تغذية رابط
auto_grabbing: السيارات الاستيلاء
start_on: ابدأ على
grab_duration: الاستيلاء مدة
item_per_grab: البند في انتزاع
edit_source: تحرير المصدر
source_updated: تحديث
news_featured: أخبار واردة
news_un_featured: أنباء الأمم المتحدة واردة
no_news: لا أنباء
featured_news: أخبار مميزة
widget_updated: القطعة محدثة
delete_selected: حذف المحدد
popular_news: الأخبار الأكثر تصفحا
search_result_for: نتائج البحث
source_type: نوع المصدر
make_featured: كن متميز
enable_cookie_policy_popup: كوكي سياسة قافزة
cookie_policy_page_url: كوكي صفحة سياسة رابط
cookie_policy: سياسة كوكي
cookie_policy_alert: هذا الموقع يستخدم الكوكيز. من خلال الاستمرار في استخدام هذا الموقع فإنك توافق على استخدامنا لملفات تعريف الارتباط.
read_more: اقرأ المزيد
i_agree: أوافق
confirmation_email : تأكيد البريد الإلكتروني
recovery_email : استرداد البريد الإلكتروني
payment_confirmation_email : دفع تأكيد البريد الإلكتروني
tracking_code : شفرة التتبع
news: أخبار
source_type: نوع المصدر
auto_translate: السيارات ترجمة
auto_translator: السيارات المترجم
from_lang: من لغة
edit_email_template: تحرير tmpl البريد الإلكتروني
web_email_settings : إعدادات البريد الإلكتروني على الويب
on: المشاركة في
news_sources: مصادر الأخبار
save_images_locally: حفظ الصور محليا
media_url_update: تحديث رابط سائل الإعلام القديمة
old_base_url: قديم قاعدة رابط
new_base_url: قاعدة جديدة رابط
grab_full_news : الاستيلاء على أخبار الكامل
disable_main_site_link : تعطيل رابط الموقع الرئيسي