---
sign_in: Identifiez-vous
sign_up: Inscription
agent_panel: Panneau Agent
admin_panel: panneau d'administration
country: Pays
city: Ville
register: Inscription
details:
view_all: Voir Tout
order_by: Trier par
none: Aucun
terms_and_conditions: Termes et conditions
reg_success_message: Votre inscription en compte est réussie. Un e-mail a été envoyé à votre adresse email. S'il vous plaît suivre ce courriel pour activer votre account.Thanks
recover: Récupérer
oops: Oups, page introuvable
address: Adresse
all: ALL
contact_us: Contactez-nous
confirmation: Confirmation
tags: tags
login: Connexion
post_not_found: Poster introuvable
view_more: Voir Plus
image:
create: Créer
send: Envoyer
contact_subject: Contact Courriel
password: Mot de passe
confirm_password: Confirmer mot de passe
all_posts: Tous les postes
no_posts: Pas de messages
title: Titre
description: Description de
status: Statut
actions: Actions
type: Type
type_something: tapez quelque chose
content: Content
category: Catégorie
all_categories: Toutes les catégories
edit_category: Modifier une catégorie
new_category: Nouvelle catégorie
edit: Modifier
delete: Supprimer
name: nom
save: enregistrez
no_parent: Aucun parent
add_another: Ajouter un autre
export_to_file: Exporter vers un fichier
options: Les options
all_pages: Toutes les pages
no_pages: Pas de pages
manage_menu: menu Gérer
menu_title: Menu Titre
menu_alias: alias Menu
show_in_menu: Afficher dans le menu
page_layout: Mise en page
content_from: Contenu de
url: URL
seo_options: options de SEO
meta_description: Meta description
key_words: Mots clés
crawl_after: Crawl après (jours)
all_plugins: tous les plugins
no_plugins: pas de plugins
name_and_version: Nom et version
change_password: Changer mot de passe
current_password: Mot de passe actuel
new_password: Nouveau mot de passe
retype_password: Confirmer le mot de passe
password_reset_info_msg: S'il vous plaît premier ensemble de votre nouveau mot de passe
edit_profile: Modifier le profil
profile_picture: profil Picture
username: Nom d'utilisateur
email: Email
first_name: Prénom
last_name: Nom
gender: Sexe
phone: Téléphone
company_name: Nom de la société
about_me: À propos de moi
facebook_account: compte Facebook
twitter_account: compte Twitter
linkedin_account: compte Linkedin
gp_account: compte Google+
account_msg: Please enter the link, without http: //
contact_email: Contact Courriel
webadmin_name: Nom Webadmin
webadmin_email: Webadmin Email
update: Mise à jour
upload: Télécharger
site_settings: Paramètres du site
site_title: Titre du site
footer_text: texte de pied
site_logo: Site Logo
site_language: Langue
site_text_direction: Site Orientation du texte
per_page: Pagination par page
default_page_layout: Mise en page par défaut
smtp_email_settings: paramètres de messagerie SMTP
smtp_email: SMTP Email
smtp_host: Hôte SMTP
smtp_port: Port SMTP
smtp_timeout: Délai SMTP
smtp_user: SMTP utilisateur
smtp_password: Mot de passe SMTP
generate_site_map: Générer Plan du site
sitemap_info_msg: NB: S'il vous plaît sélectionner celui que vous voulez être inclus sur la sitemap XML. Après sitemap.xml génération succès est enregistré sous le répertoire racine. Vous pouvez également éditer ce fichier pour inclure vos propres URL.
pages: Pages
view_xml: Voir le XML
create_xml: Créer XML
manage_backups: gérer les sauvegardes
create_sql_backup: Créer sauvegarde SQL
create_image_backup: Créer une image de sauvegarde
restore: Restaurer
download: Télécharger
dashboard: tableau de bord
overview_stats_more: Vue d'ensemble, statistiques et plus
visit_site: Visite du site
logout: Déconnexion
themes: Thèmes
locations: emplacements
profile:
agents: Agents
widgets: Widgets
all_widgets: tous les widgets
widget_positions: Positions Widget
new_post: Nouveau message
pages_and_menu: Pages & Menu
new_page: Nouvelle page
menu: Menu
system: Système
edit_email_text: Modifier Email texte
admin_settings: Paramètres administrateur Web
sitemap: Plan du site
activate: Activez
active_theme: Actif Thème
available_themes: Thèmes disponibles
all_users: Tous les utilisateurs
create_user: Créer un utilisateur
export_user_email: Emails exportation de l'utilisateur (.csv)
profile_info: Profil Infos
manage_menu: Gérer Menu
edit_page: Modifier la page
create_widget: Créer Widget
widget_name: Nom Widget
activate_deactivate: Activer / désactiver
show: Montrer
available_widgets: Disponible Widgets
active_widgets: Widgets actifs
delete_warning: Voulez-vous vraiment ne supprimer.
yes: oui'
no:non'
fa_icon: FA icône classe
post_ad: Publier
post_ad_subtitle: Mettez votre détail de l'annonce
signin: Signin
signup: Inscription
signup_title: Créer votre compte
not_found: Introuvable
purpose: But
select_category: Choisir une catégorie
address: Adresse
upload_later_msg: Vous serez en mesure de télécharger la galerie photos et vidéo url après la création de poste
user_panel: panneau de l'utilisateur
logout: Déconnexion
all_posts: Tous les postes
put_as_comma_seperated: mis comme (,) virgule sperated
added: Ajouté
location:
views: Vues
add_new: Ajouter un nouveau
search: Chercher
contact_mode: Mode de contact
reset:
contact: Contactez-
type_your_message: Tapez votre message ici ..
mail_sent: mail envoyé
home: Accueil
list_your_ad: Votre liste d'annonces
print: Imprimer
remember_me: Se souvenir de moi
forgot_password: Mot de passe oublié
login_to_your_account: Connectez-vous à votre compte
register_your_account: Enregistrez votre compte
male: Homme
female: Femme
state: Etat
users: les utilisateurs
ads:
categories: Catégories
top_posts: Top Posts
default_site_settings: Paramètres du site par défaut
webadmin_settings: Réglages de WebAdmin
banner_settings: Réglages Banner
logged_in_as: Connecté en tant que
password_change_success: Mot de passe changé avec succès
email_sent_inbox: Un email est envoyé à votre inbox.Check ce courriel.
password_recovery_link_invalid: Password Recovery lien ne semble pas valide
user_updated: utilisateur mise à jour
user_deleted: utilisateur supprimé
data_inserted: données insérées
data_updated: données mises à jour
settings_updated: paramètres mis à jour
page_updated: Page mise à jour
page_created: page créée
page_deleted: page supprimée
menu_updated: Menu Mise à jour
site_map_generation_success: Plan du site généré avec succès.
select_option: S'il vous plaît sélectionner sur choisis ou plus d'options.
image_backup_created: image de sauvegarde créée
language_translated: Langue Traduit
backup_deleted: sauvegarde supprimée
database_restored: base de données restaurée
theme_activated: Thème Activé
user_created: l'utilisateur Créé
widget_position_updated: Widget Postion Mise à jour
widget_created: Widget Créé
settings_updated: paramètres mis à jour
widget_data_updated: Widget données mises à jour
unable_to_write_widget: Impossible d'écrire un widget
admin_change_pass_help: Laisser en blanc si aucun changement nécessaire
login_with_google: Connectez-vous avec Google
login_with_facebook: Connectez-vous avec Facebook
register_for_new_account : Enregistrement de nouveau compte
site_map : Plan du site
show_site_map : Voir la carte du site
about : A propos de
see_full_documentation: Voir documentation complète
edit_profile: Modifier le profil
admin: admin
re_password: Confirmer le mot de passe
explain_widget_position: Expliquez positions de widgets
new_ad: Nouvelle annonce
select_one: Choisir
username_or_email: Nom d'utilisateur ou e-mail
post_detail: Poster détail
edit_user: Modifier l'utilisateur
the_field_is_required: le champ% est nécessaire.
valid_email: le champ% doit contenir une adresse email valide.
min_length: le champ% doit être au moins caractères% s de longueur.
numeric: le champ% doit contenir que des chiffres.
matches: le champ% ne correspond pas au domaine de l'%.
greater_than: le champ% doit contenir un nombre supérieur à% s.
must_accept_terms: Vous devez accepter les termes et conditions
dont_have_permission: Vous n'êtes pas autorisé à accéder à cette page
email_allready_in_use: Email déjà utilisé
username_allready_in_use: Nom d'utilisateur deja en cours d'utilisation
current_password_not_matched: Mot de passe actuel n \ 't correspondance
email_not_matched: Email pas égalé
account_not_confirmed: Compte non confirmé
unique_alias: le champ% doit être unique
smtp_email_settings: paramètres de messagerie SMTP
error_occured: Une erreur est survenue. S'il vous plaît vérifier les champs ci-dessous
user_profile: le profil de l'utilisateur '
user_email: e-mail de l'utilisateur
target_lang_name: Langue cible
enable_signup: Activer votre inscription
facebook_app_settings: Facebook paramètres de l'application
enable_facebook_login: Activer Facebook Login
fb_app_id: Facebook app id
fb_secret_key: clé secrète Facebook
comment_settings: Paramètres des commentaires
enable_comment: Activer commentaire
disqus_shortname: Disqus abrégé
active_widget_position: active la position du widget
upload_and_install: Télécharger et installer
install_updates: installer les mises / Thèmes / Plugins / Widgets
click_and_edit: Sélectionnez un fichier de modèle et cliquez sur Modifier
google_analytics_settings: AnalyticsSettings Google
default_seo_settings: paramètres de référencement par défaut
find_us_on_facebook: Retrouvez-nous sur Facebook
type_anything: tapez rien
login_failed : Échec de la connexion
debug_email : Debug email
email_to : Pour envoyer un courriel
ive_read_the: Je l'ai lu
title_city_category: Titre, Ville ou Catégorie
css_compression: Fusionner tous les fichiers CSS
all_sub_categories : toutes les sous catégories
no_sub_categories : Aucun Sous-catégories
email_cleared: Email effacé
hide_users_profile_phone: Masquer les utilisateurs profil téléphone
features: Caractéristiques
content: Content
news_urls: nouvelle source
all_sources: Toutes les sources
addsource: Ajouter la source
new_source: Une nouvelle source
seo_keywords : seo_keywords Seo
seo_description : Seo description
all_news : Toutes les Nouvelles
new_news : New Nouvelles
create_news : Créez Nouvelles
edit_news : Modifier Nouvelles
no_source : Aucune Source
no_category : Non Catégorie
sub_category : Sous catégorie
category_2: S.Category
news_updated: Nouvelles mises à jour
news_added: Nouvelles créée
source: Source
link: Link
media: Média
put_as_comma_separated: Mettez en virgule (,) format séparé
site_settings: Paramètres du site
clear_old_news: Effacer vieilles nouvelles
news_before: Nouvelles avant
leave_empty_if_doesnot_matter: Laisser vide si vous n'a pas d'importance
view_less_than: Voir moins
without_image: Sans image
you_cant_undo_this_action: Vous ne pouvez pas annuler cette action
news_deleted: Nouvelles effacé
general: général
moderator:
genaral_user_can_create_post: l'utilisateur peut créer des nouvelles
moderator_can_create_post: Modérateur peut créer nouvelles
auto_crawl: Auto crawl
lazy_load_images: images lazy loading
generate_widgets: générer des widgets
sidebar: Sidebar
pagebody: PageBody
widget_generated: Widget généré
widget_generation_failed: génération Widget échoué
latest_news: Dernières Nouvelles
news_by: Par
top_news: Nouvelles Top
source_added: Source Ajouté
no_news_found: Pas de nouvelles
clear: Effacer
view_news_in: Voir nouvelles dans
seen_by: Voir
read_this_on: Lisez ceci sur
news_source: Nouvelles provenant d'une source
news_category: Nouvelles d'une catégorie
source_name: Nom
parent_category: Catégorie parente
news_grabbed: Nouvelles saisi avec succès
rss_url: URL du flux
auto_grabbing: Auto accaparement
start_on: Démarrer sur
grab_duration: durée Grab
item_per_grab: Article par grab
edit_source: Modifier la source
source_updated: Source mis à jour
news_featured: Nouvelles beta
news_un_featured: Nouvelles de l'ONU en vedette
no_news: Pas de nouvelles
featured_news: vedette Nouvelles
widget_updated: Widget mis à jour
delete_selected: Effacer la sélection
popular_news: Nouvelles populaires
search_result_for: Résultat de la recherche
source_type: Type de Source
make_featured: Faites sélectionnée
enable_cookie_policy_popup: Cookie Policy Popup
cookie_policy_page_url: Cookie page politique URL
cookie_policy: politique de Cookie
cookie_policy_alert: Ce site utilise des cookies. En continuant à utiliser ce site, vous acceptez notre utilisation des cookies.
read_more: Lire la suite
i_agree: Je suis d'accord
confirmation_email : Confirmation email
recovery_email : Récupération email
payment_confirmation_email : paiement email de confirmation
tracking_code : Code de suivi
news: Nouvelles
source_type: Type de Source
auto_translate: Traduire Auto
auto_translator: Auto Translator
from_lang: De la langue
edit_email_template: Modifier email tmpl
web_email_settings : paramètres de messagerie Web
on: Posté le
news_sources: Sources Nouvelles
save_images_locally: Sauvegardez les images localement
media_url_update: Mise à jour URL vieux médias
old_base_url: Old url de base
new_base_url: New URL de base
grab_full_news: Faire pleine nouvelles
disable_main_site_link: Désactiver principal lien du site